Mums-Who-Code/SCMS.Services

SCMS.Services.Api/Brokers/Storages/IStorageBroker.StudentGuardian.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.StudentGuardian.cs

BROKERS: Insert StudentGuardian

---

SCMS.Services.Api/Brokers/Storages/StorageBroker.Guardian.References.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.School.References.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.Student.References.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.StudentSchool.References.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.cs

CODE RUB: Change references method name from Add to Set

---

SCMS.Services.Api/Startup.cs

CODE RUB: Change Broker Registration to Transient

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.Student.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.Student.cs

closes [#95](https://github.com/Mums-Who-Code/SCMS.Services/issues/95)

BROKER: Select All Students

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.Student.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.Student.cs

BROKER: Select Student By Id

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.Student.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.Student.cs

BROKER: Update Student

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.StudentGuardian.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.StudentGuardian.cs

BROKERS: Get All Student Guardians

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.School.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.School.cs

BROKER: Select All Schools

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.StudentSchool.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.StudentSchool.cs

BROKER: Select All Student School

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.Student.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.Student.cs

BROKER: Delete Student

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.School.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.School.cs

BROKER: Select School By Id

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.Guardian.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.Guardian.cs

BROKER: Select All Guradian

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.StudentSchool.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.StudentSchool.cs

BROKER: Select By Id Student School

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.School.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.School.cs

BROKER: Update School 

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.StudentSchool.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.StudentSchool.cs

BROKER: Update Student School

---

SCMS.Services.Api/Models/Foundations/StudentGuardians/Exceptions/AlreadyExistsStudentGuardianException.cs
SCMS.Services.Api/Models/Foundations/StudentGuardians/Exceptions/FailedStudentGuardianServiceException.cs
SCMS.Services.Api/Models/Foundations/StudentGuardians/Exceptions/FailedStudentGuardianStorageException.cs
SCMS.Services.Api/Models/Foundations/StudentGuardians/Exceptions/InvalidStudentGuardianException.cs
SCMS.Services.Api/Models/Foundations/StudentGuardians/Exceptions/InvalidStudentGuardianReferenceException.cs
SCMS.Services.Api/Models/Foundations/StudentGuardians/Exceptions/NullStudentGuardianException.cs
SCMS.Services.Api/Models/Foundations/StudentGuardians/Exceptions/StudentGuardianDependencyException.cs
SCMS.Services.Api/Models/Foundations/StudentGuardians/Exceptions/StudentGuardianDependencyValidationException.cs
SCMS.Services.Api/Models/Foundations/StudentGuardians/Exceptions/StudentGuardianServiceException.cs
SCMS.Services.Api/Models/Foundations/StudentGuardians/Exceptions/StudentGuardianValidationException.cs
SCMS.Services.Api/Services/Foundations/StudentGuardians/IStudentGuardianService.cs
SCMS.Services.Api/Services/Foundations/StudentGuardians/StudentGuardianService.Exceptions.cs
SCMS.Services.Api/Services/Foundations/StudentGuardians/StudentGuardianService.Validations.cs
SCMS.Services.Api/Services/Foundations/StudentGuardians/StudentGuardianService.cs
SCMS.Services.Api/Startup.cs
SCMS.Services.Tests.Unit/Services/Foundations/StudentGuardians/StudentGuardianServiceTests.Exceptions.Add.cs
SCMS.Services.Tests.Unit/Services/Foundations/StudentGuardians/StudentGuardianServiceTests.Logic.Add.cs
SCMS.Services.Tests.Unit/Services/Foundations/StudentGuardians/StudentGuardianServiceTests.Validations.Add.cs
SCMS.Services.Tests.Unit/Services/Foundations/StudentGuardians/StudentGuardianServiceTests.cs

FOUNDATIONS: Add Student Guardian

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.Guardian.cs
SCMS.Services.Api/Brokers/Storages/IStorageBroker.School.cs
SCMS.Services.Api/Brokers/Storages/IStorageBroker.StudentGuardian.cs
SCMS.Services.Api/Brokers/Storages/IStorageBroker.StudentSchool.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.Guardian.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.School.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.StudentSchool.cs
SCMS.Services.Api/Services/Foundations/StudentGuardians/IStudentGuardianService.cs
SCMS.Services.Api/Services/Foundations/StudentGuardians/StudentGuardianService.Exceptions.cs
SCMS.Services.Api/Services/Foundations/StudentGuardians/StudentGuardianService.cs
SCMS.Services.Tests.Unit/Services/Foundations/StudentGuardians/StudentGuardianServiceTests.Exceptions.RetrieveAll.cs
SCMS.Services.Tests.Unit/Services/Foundations/StudentGuardians/StudentGuardianServiceTests.Logic.RetrieveAll.cs
SCMS.Services.Tests.Unit/Services/Foundations/StudentGuardians/StudentGuardianServiceTests.cs

FOUNDATIONS: Retrieve All Student Guardians

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.School.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.School.cs

BROKER: Delete School

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.StudentSchool.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.StudentSchool.cs

BROKER: Delete Student School

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.Guardian.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.Guardian.cs

BROKER: Select By Id Guardian

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.StudentGuardian.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.StudentGuardian.cs

BROKER: Select By Id Student Guardian

---

SCMS.Services.Api/Models/Processings/StudentGuardians/Exceptions/AlreadyExistsPrimaryStudentGuardianProcessingException.cs
SCMS.Services.Api/Models/Processings/StudentGuardians/Exceptions/FailedStudentGuardianProcessingServiceException.cs
SCMS.Services.Api/Models/Processings/StudentGuardians/Exceptions/InvalidStudentGuardianProcessingException.cs
SCMS.Services.Api/Models/Processings/StudentGuardians/Exceptions/NullStudentGuardianProcessingException.cs
SCMS.Services.Api/Models/Processings/StudentGuardians/Exceptions/StudentGuardianProcessingDependencyException.cs
SCMS.Services.Api/Models/Processings/StudentGuardians/Exceptions/StudentGuardianProcessingDependencyValidationException.cs
SCMS.Services.Api/Models/Processings/StudentGuardians/Exceptions/StudentGuardianProcessingServiceException.cs
SCMS.Services.Api/Models/Processings/StudentGuardians/Exceptions/StudentGuardianProcessingValidationException.cs
SCMS.Services.Api/Models/Processings/StudentGuardians/Exceptions/StudentGuardianValidationProcessingException.cs
SCMS.Services.Api/Services/Processings/StudentGuardians/IStudentGuardianProcessingService.cs
SCMS.Services.Api/Services/Processings/StudentGuardians/StudentGuardianProcessingService.Exceptions.cs
SCMS.Services.Api/Services/Processings/StudentGuardians/StudentGuardianProcessingService.Validations.cs
SCMS.Services.Api/Services/Processings/StudentGuardians/StudentGuardianProcessingService.cs
SCMS.Services.Api/Startup.cs
SCMS.Services.Tests.Unit/Services/Processings/StudentGuardians/StudentGuardianProcessingTests.Exceptions.Add.cs
SCMS.Services.Tests.Unit/Services/Processings/StudentGuardians/StudentGuardianProcessingTests.Logic.Add.cs
SCMS.Services.Tests.Unit/Services/Processings/StudentGuardians/StudentGuardianProcessingTests.Validations.Add.cs
SCMS.Services.Tests.Unit/Services/Processings/StudentGuardians/StudentGuardianProcessingTests.cs

PROCESSINGS: Add Student Guardian

---

SCMS.Services.Api/Controllers/StudentGuardiansController.cs

CONTROLLER: POST Student Guardian

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.Phone.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.Phone.cs
SCMS.Services.Api/Migrations/20211130015856_AdditionalDetailRelations.cs

BROKER: Select All Phone

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.Phone.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.Phone.cs

BROKER: Select By Id Phone

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.AdditionalDetail.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.AdditionalDetail.cs

BROKER: Insert Additional Details

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.Email.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.Email.cs

BROKER: Insert Email

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.AdditionalDetail.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.AdditionalDetail.cs

BROKER: Select All Additional Details

---

SCMS.Services.Api/Brokers/Storages/StorageBroker.AdditionalDetail.cs

Closes #[184](https://github.com/Mums-Who-Code/SCMS.Services/issues/184)

BROKER: Select By Id Additional Details 

---

SCMS.Services.Api/Brokers/Storages/StorageBroker.AdditionalDetail.cs

Closes #[186](https://github.com/Mums-Who-Code/SCMS.Services/issues/186)

BROKER: Delete Additional Details

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.Occupation.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.Occupation.cs

BROKER: Insert Occupation

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.Phone.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.Phone.cs

BROKER: Delete Phone

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.AdditionalDetail.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.AdditionalDetail.cs

Closes #[185](https://github.com/Mums-Who-Code/SCMS.Services/issues/185)

BROKER: Update Additional Details

---

SCMS.Services.Api/Brokers/Storages/IStorageBroker.Email.cs
SCMS.Services.Api/Brokers/Storages/StorageBroker.Email.cs

BROKER: Select All Email

---

SCMS.Services.Api/Services/Foundations/Schools/ISchoolService.cs
SCMS.Services.Api/Services/Foundations/Schools/SchoolService.Exceptions.cs
SCMS.Services.Api/Services/Foundations/Schools/SchoolService.cs
SCMS.Services.Tests.Unit/Services/Foundations/Schools/SchoolServiceTests.Exceptions.RetrieveAll.cs
SCMS.Services.Tests.Unit/Services/Foundations/Schools/SchoolServiceTests.Logic.RetrieveAll.cs
SCMS.Services.Tests.Unit/Services/Foundations/Schools/SchoolServiceTests.cs

FOUNDATIONS: Retrieve All Schools

---

SCMS.Services.Api/Controllers/SchoolsController.cs
SCMS.Services.Api/SCMS.Services.Api.csproj
SCMS.Services.Api/Services/Foundations/Schools/SchoolService.Exceptions.cs
SCMS.Services.Api/Startup.cs

CONTROLLER: Get All Schools

---

SCMS.Services.Api/Controllers/GuardianRequestsController.cs
SCMS.Services.Api/Services/Orchestrations/StudentGuardianRequests/StudentGuardianRequestOrchestrationService.Validations.cs

CONTROLLER: POST Guardian Request

---

.github/workflows/dotnet.yml
SCMS.Services.Api/SCMS.Services.Api.csproj
SCMS.Services.Infrastructure.Build/Program.cs
SCMS.Services.Infrastructure.Build/SCMS.Services.Infrastructure.Build.csproj
SCMS.Services.Infrastructure.Provision/SCMS.Services.Infrastructure.Provision.csproj
SCMS.Services.Tests.Acceptance/SCMS.Services.Tests.Acceptance.csproj
SCMS.Services.Tests.Unit/SCMS.Services.Tests.Unit.csproj

CONFIG: Updated .NET Version
